pool:
  vmImage: 'windows-latest'

stages:
  - stage: get commandbox
    jobs:
    - job: Lucee4
      steps:
      - script: |
          echo Starting the build
          curl --location -o /tmp/box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
          unzip /tmp/box.zip -d /tmp/