pool:
  vmImage: 'ubuntu-16.04'

stages:
  - stage: Testing
    jobs:
    - job: Lucee4
      steps:
      - script: |
          echo Starting the build
          curl --location -o /tmp/box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
          unzip /tmp/box.zip -d /tmp/
          chmod a+x /tmp/box
          /tmp/box install production=false
          /tmp/box server start cfengine=lucee@4
          mkdir /tmp/results/
          /tmp/box testbox run outputFile=testbox-lucee4.xml reporter=junit
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/testbox-*.xml' 
          testRunTitle: TestBox Tests
          failTaskOnFailedTests: true
        displayName: 'TestBox Results'
    - job: Lucee5
      steps:
      - script: |
          echo Starting the build
          curl --location -o /tmp/box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
          unzip /tmp/box.zip -d /tmp/
          chmod a+x /tmp/box
          /tmp/box install production=false
          /tmp/box server start cfengine=lucee@5
          mkdir /tmp/results/
          /tmp/box testbox run outputFile=testbox-lucee5.xml reporter=junit
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/testbox-*.xml' 
          testRunTitle: TestBox Tests
          failTaskOnFailedTests: true
        displayName: 'TestBox Results'
    - job: Adobe10
      steps:
      - script: |
          echo Starting the build
          curl --location -o /tmp/box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
          unzip /tmp/box.zip -d /tmp/
          chmod a+x /tmp/box
          /tmp/box install production=false
          /tmp/box server start cfengine=adobe@10
          mkdir /tmp/results/
          /tmp/box testbox run outputFile=testbox-adobe10.xml reporter=junit
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/testbox-*.xml' 
          testRunTitle: TestBox Tests
          failTaskOnFailedTests: true
        displayName: 'TestBox Results'
    - job: Adobe11
      steps:
      - script: |
          echo Starting the build
          curl --location -o /tmp/box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
          unzip /tmp/box.zip -d /tmp/
          chmod a+x /tmp/box
          /tmp/box install production=false
          /tmp/box server start cfengine=adobe@11
          mkdir /tmp/results/
          /tmp/box testbox run outputFile=testbox-adobe11.xml reporter=junit
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/testbox-*.xml' 
          testRunTitle: TestBox Tests
          failTaskOnFailedTests: true
        displayName: 'TestBox Results'
    - job: Adobe16
      steps:
      - script: |
          echo Starting the build
          curl --location -o /tmp/box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
          unzip /tmp/box.zip -d /tmp/
          chmod a+x /tmp/box
          /tmp/box install production=false
          /tmp/box server start cfengine=adobe@2016
          mkdir /tmp/results/
          /tmp/box testbox run outputFile=testbox-adobe16.xml reporter=junit
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/testbox-*.xml' 
          testRunTitle: TestBox Tests
          failTaskOnFailedTests: true
        displayName: 'TestBox Results'
    - job: Adobe18
      steps:
      - script: |
          echo Starting the build
          curl --location -o /tmp/box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
          unzip /tmp/box.zip -d /tmp/
          chmod a+x /tmp/box
          /tmp/box install production=false
          /tmp/box server start cfengine=adobe@2018
          mkdir /tmp/results/
          /tmp/box testbox run outputFile=testbox-adobe18.xml reporter=junit
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/testbox-*.xml' 
          testRunTitle: TestBox Tests
          failTaskOnFailedTests: true
        displayName: 'TestBox Results'